### ISSUE TITLE
Error in `gtbook.discrete.show()`

### ISSUE THREAD

**Issue by AbhineetJain** [gtbook/gtbook#3]
Hello Prof. Dellaert,

When executing the `S32_vacuum_actions` Colab from https://www.roboticsbook.org/S32_vacuum_actions.html, we are running into the following error:

```---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: Unregistered type : std::set<unsigned long, std::less<unsigned long>, std::allocator<unsigned long> >

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
[<ipython-input-6-4c1425e2b058>](https://localhost:8080/#) in <module>
      2 fragment = gtsam.DiscreteBayesNet()
      3 fragment.add(motion_model)
----> 4 show(fragment, hints={"A":2, "X":1}, boxes={A[1][0], X[1][0]})

2 frames
[<ipython-input-2-23c57660802c>](https://localhost:8080/#) in show(obj, **kwargs)
     11     return gtbook.display.pretty(obj, VARIABLES)
     12 def show(obj, **kwargs):
---> 13     return gtbook.display.show(obj, VARIABLES, **kwargs)
     14 
     15 # From section 3.1:

[/usr/local/lib/python3.8/dist-packages/gtbook/display.py](https://localhost:8080/#) in __init__(self, obj, *args, **kwargs)
     28 
     29         # Check if a DotWriter needs creating (or amending)
---> 30         writer = dbn_writer(**kwargs)
     31         if writer is not None:
     32             kwargs = {"writer": writer}

[/usr/local/lib/python3.8/dist-packages/gtbook/dbn.py](https://localhost:8080/#) in dbn_writer(writer, hints, positions, boxes, factor_positions, binary_edges, **kwargs)
     42     if boxes is not None:
     43         assert isinstance(boxes, set)
---> 44         bx: set = writer.boxes
     45         for key in boxes:
     46             bx.add(key)

TypeError: Unable to convert function return value to a Python type! The signature was
	(self: gtsam.gtsam.DotWriter) -> std::set<unsigned long, std::less<unsigned long>, std::allocator<unsigned long> >

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.
```

I tried debugging, but was not sure what caused the issue. Can you suggest a fix to this? It is currently blocking the release of Project 2 for CS3630 at Georgia Tech as well.

Thank you!

**Comment by dellaert** [comment]
Let me take a look. What;'s the timing/deadline?

**Comment by AbhineetJain** [comment]
> Let me take a look. What;'s the timing/deadline?

We are planning to release this late Monday evening (Jan 30). I understand it is a short term, my apologies for that. I am available to help as much as I can in resolving this. I wonder if we can release the assignment and communicate the fix later as we get to the solution.

**Comment by dellaert** [comment]
> > Let me take a look. What;'s the timing/deadline?
> 
> We are planning to release this late Monday evening (Jan 30). I understand it is a short term, my apologies for that. I am available to help as much as I can in resolving this. I wonder if we can release the assignment and communicate the fix later as we get to the solution.

No, that's not a great idea. I'll take a look today or at latest Saturday

**Comment by AbhineetJain** [comment]
> > > Let me take a look. What;'s the timing/deadline?
> > 
> > 
> > We are planning to release this late Monday evening (Jan 30). I understand it is a short term, my apologies for that. I am available to help as much as I can in resolving this. I wonder if we can release the assignment and communicate the fix later as we get to the solution.
> 
> No, that's not a great idea. I'll take a look today or at latest Saturday

Thank you so much, Frank. Please let me know if I can be of any help.

**Comment by dellaert** [comment]
This is so weird. Not seeing this with version 4.2a8 on my mac, but *do* see it on colab :-(

**Comment by AbhineetJain** [comment]
> This is so weird. Not seeing this with version 4.2a8 on my mac, but _do_ see it on colab :-(

Yeah, that is weird. Are there any version specifications that we can do on Colab?

**Comment by dellaert** [comment]
For the assignment, a workaround is to not use the boxes argument. 

PS I have spent some time trying to fix the underlying issue but it is harder than I thought - as I am running into python versioning issues. Try the workaround?

**Comment by AbhineetJain** [comment]
> For the assignment, a workaround is to not use the boxes argument.
> 
> PS I have spent some time trying to fix the underlying issue but it is harder than I thought - as I am running into python versioning issues. Try the workaround?

The workaround works perfectly fine 🤯 Thank you so much for working on this at such short notice! ❤️ I wonder if it depends on different python versions used in gtsam, gtbook and Colab somehow?

**Comment by dellaert** [comment]
gtbook was updated to 0.0.31 and now loads a new version of GTSAM, 4.2a9. Please *do* let me know when you run into issues again, I am about to release GTSAM 4.2 and would love to know if there other things wrong. Thanks !

**Comment by AbhineetJain** [comment]
Thank you, Prof. Dellaert! We'll keep you posted if we run into any other issues.
